/*TABLA RANGO*/
CREATE TABLE RANGO 
(
	RANGO_ID serial PRIMARY KEY,
	RANGO_NOMBRE varchar(30),
	RANGO_DESCRIPCION varchar(60),
	RANGO_ANTERIOR varchar(30),
	RANGO_A_NECESARIO smallint,
	RANGO_P_EVALUAR varchar(60)
);


/*TABLA CALIFICACIÓN*/
CREATE TABLE CALIFICACION 
(
	CALIFICACION_ID serial PRIMARY KEY,
	CALIFICACION_NOMBRE varchar(30),
	CALIFICACION_DESCRIPCION varchar(30)
);


/*TABLA BATALLON*/
CREATE TABLE BATALLON
(
	BATALLON_ID serial PRIMARY KEY,
	BATALLON_NUMERO smallint,
	BATALLON_ALIAS varchar(30)
);


/*TABLA ENTRENAMIENTO*/
CREATE TABLE ENTRENAMIENTO
(
	ENTRENAMIENTO_ID serial PRIMARY KEY,
	ENTRENAMIENTO_F_INICIO date,
	ENTRENAMIENTO_F_TERMINO date,
	BATALLON_ID BIGINT UNSIGNED NOT NULL,
	CALIFICACION_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT ENTRENAMIENTO_BATALLON_FK FOREIGN KEY (BATALLON_ID) REFERENCES BATALLON (BATALLON_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ENTRENAMIENTO_CALIFICACION_FK FOREIGN KEY (CALIFICACION_ID) REFERENCES CALIFICACION (CALIFICACION_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE
);


/*TABLA SOLDADO*/
CREATE TABLE SOLDADO
(
	SOLDADO_ID serial PRIMARY KEY,
	SOLDADO_NOMBRE varchar(30),
	SOLDADO_APELLIDO varchar(30),
	SOLDADO_CI varchar(30),
	SOLDADO_GENERO VARCHAR(15),
	SOLDADO_F_NACIMIENTO date,
	SOLDADO_F_INGRESO date,
	SOLDADO_N_TATUAJE smallint,
	RANGO_ID BIGINT UNSIGNED NOT NULL,
	BATALLON_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT SOLDADO_RANGO_FK FOREIGN KEY (RANGO_ID) REFERENCES RANGO (RANGO_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT SOLDADO_BATALLON_FK FOREIGN KEY (BATALLON_ID) REFERENCES BATALLON (BATALLON_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE
);


/*TABLA CASTIGO*/
CREATE TABLE CASTIGO
(
	CASTIGO_ID serial PRIMARY KEY,
	CASTIGO_F_INCIDENTE date,
	CASTIGO_F_INICIO date,
	CASTIGO_F_TERMINO date,
	CASTIGO_MOTIVO varchar(60),
	SANCIONADO_ID BIGINT UNSIGNED NOT NULL,
	SANCIONADOR_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT CASTIGO_SANCIONADO_FK FOREIGN KEY (SANCIONADO_ID) REFERENCES SOLDADO (SOLDADO_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT CASTIGO_SANCIONADOR_FK FOREIGN KEY (SANCIONADOR_ID) REFERENCES SOLDADO (SOLDADO_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE
);


/*TABLA PETICION ASCENSO*/
CREATE TABLE PETICION_ASCENSO
(
	PETICION_ASCENSO_ID serial PRIMARY KEY,
	ASPIRANTE_ID BIGINT UNSIGNED NOT NULL,
	PETICION_ASCENSO_FECHA date,
	PETICION_ASCENSO_N_T_ENCONTRADOS smallint,
	RANGO_ACTUAL_ID BIGINT UNSIGNED NOT NULL,
	RANGO_ASCENDER_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT ASCENSO_RANGO_ACTUAL_FK FOREIGN KEY (RANGO_ACTUAL_ID) REFERENCES RANGO (RANGO_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ASCENSO_RANGO_ASCENDER_FK FOREIGN KEY (RANGO_ASCENDER_ID) REFERENCES RANGO (RANGO_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ASCENSO_SOLDADO_FK FOREIGN KEY (ASPIRANTE_ID) REFERENCES SOLDADO (SOLDADO_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE
);


/*TABLA ASCENSO*/
CREATE TABLE ASCENSO
(
	ASCENSO_ID serial PRIMARY KEY,
	ASCENSO_FECHA date,
	PETICION_ASCENSO_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT ASCENSO_PETICION_ASCENSO_FK FOREIGN KEY (PETICION_ASCENSO_ID) REFERENCES PETICION_ASCENSO (PETICION_ASCENSO_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE
);