/*TABLA HISTORIAL TATUAJE*/

CREATE TABLE historial_tatuaje
(
    HT_ID SERIAL PRIMARY KEY,
    S_ID BIGINT UNSIGNED NOT NULL,
    S_N_ANTERIOR_TATUAJES smallint,
    S_N_NUEVO_TATUAJES smallint,
    HT_FECHA DATETIME,
    CONSTRAINT S_ID_FK FOREIGN KEY (S_ID) REFERENCES SOLDADO (SOLDADO_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE
);
