/*TABLA CALIFICACIÓN*/

CREATE TABLE CALIFICACION 
(
	CALIFICACION_ID serial PRIMARY KEY,
	CALIFICACION_NOMBRE varchar(30),
	CALIFICACION_DESCRIPCION varchar(30)
);

/*INGRESAR VALORES PARA CALIFICACIÓN*/
	
INSERT INTO CALIFICACION (CALIFICACION_NOMBRE,CALIFICACION_DESCRIPCION) 
VALUES('REGULAR','CALIFICACION MALA');
INSERT INTO CALIFICACION (CALIFICACION_NOMBRE,CALIFICACION_DESCRIPCION) 
VALUES('BUENA','CALIFICACION MEDIA');
INSERT INTO CALIFICACION (CALIFICACION_NOMBRE,CALIFICACION_DESCRIPCION)
VALUES('EXCELENTE','CALIFICACION BUENA');