/*TABLA RANGO*/

CREATE TABLE RANGO 
(
	RANGO_ID serial PRIMARY KEY,
	RANGO_NOMBRE varchar(30),
	RANGO_DESCRIPCION varchar(60),
	RANGO_ANTERIOR varchar(30),
	RANGO_A_NECESARIO smallint,
	RANGO_P_EVALUAR varchar(60)
);

/*INGRESAR VALORES PARA RANGO*/

INSERT INTO RANGO (RANGO_NOMBRE,RANGO_DESCRIPCION,RANGO_ANTERIOR,RANGO_A_NECESARIO,RANGO_P_EVALUAR)
VALUES('SOLDADO','TROPA MENOR',NULL,0,'PRUEBAS FÍSICAS NECESARIAS');
INSERT INTO RANGO (RANGO_NOMBRE,RANGO_DESCRIPCION,RANGO_ANTERIOR,RANGO_A_NECESARIO,RANGO_P_EVALUAR)
VALUES('SARGENTO','A CARGO DE LOS SOLDADOS', 'SOLDADO',4,'PRUEBA DE HISTORIA Y FÍSICAS');
INSERT INTO RANGO (RANGO_NOMBRE,RANGO_DESCRIPCION,RANGO_ANTERIOR,RANGO_A_NECESARIO,RANGO_P_EVALUAR)
VALUES('SUBOFICIAL','A CARGO DE LOS SARGENTOS','SARGENTO',6,'PRUEBAS DE HISTORIA Y FÍSICAS');
INSERT INTO RANGO (RANGO_NOMBRE,RANGO_DESCRIPCION,RANGO_ANTERIOR,RANGO_A_NECESARIO,RANGO_P_EVALUAR)
VALUES('OFICIAL SUBALTERNO','SU INSIGNIA ES UNA ESTRELLA PLATEADA', 'SUBOFICIAL',8,'PRUEBA DE LEYES, HISTORIA Y FÍSICAS');
INSERT INTO RANGO (RANGO_NOMBRE,RANGO_DESCRIPCION,RANGO_ANTERIOR,RANGO_A_NECESARIO,RANGO_P_EVALUAR)
VALUES('OFICIAL SUPERIOR','SU INSIGNIA ES UNA ESTRELLA DORADA', 'OFICIAL SUBALTERNO',10,'PRUEBA DE LEYES, HISTORIA Y FÍSICAS');
INSERT INTO RANGO (RANGO_NOMBRE,RANGO_DESCRIPCION,RANGO_ANTERIOR,RANGO_A_NECESARIO,RANGO_P_EVALUAR)
VALUES('OFICIAL GENERAL','SU INSIGNIA ES EL ESCUDO DE LA REPUBLICA DEL ECUADOR', 'OFICIAL SUPERIOR',14,'PRUEBBA DE DERECHO, LEYES, HISTORIA Y FÍSICAS');