/*TABLA ASCENSO*/

CREATE TABLE ASCENSO
(
	ASCENSO_ID serial PRIMARY KEY,
	ASCENSO_FECHA date,
	PETICION_ASCENSO_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT ASCENSO_PETICION_ASCENSO_FK FOREIGN KEY (PETICION_ASCENSO_ID) REFERENCES PETICION_ASCENSO (PETICION_ASCENSO_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE
);

/*INGRESAR VALORES EN ASCENSO*/

INSERT INTO ASCENSO (ASCENSO_FECHA,PETICION_ASCENSO_ID)
VALUES ('2016-01-01',1);

INSERT INTO ASCENSO (ASCENSO_FECHA,PETICION_ASCENSO_ID)
VALUES ('2008-05-01',7);