/*TABLA BATALLON*/

CREATE TABLE BATALLON
(
	BATALLON_ID serial PRIMARY KEY,
	BATALLON_NUMERO smallint,
	BATALLON_ALIAS varchar(30)
);

/*INGRESAR VALORES PARA BATALLON*/

INSERT INTO BATALLON (BATALLON_NUMERO,BATALLON_ALIAS) VALUES(10,'MEGATOS');
INSERT INTO BATALLON (BATALLON_NUMERO,BATALLON_ALIAS) VALUES(8,'BRIGADIER');
INSERT INTO BATALLON (BATALLON_NUMERO,BATALLON_ALIAS) VALUES(20,'PAQUISHA');
INSERT INTO BATALLON (BATALLON_NUMERO,BATALLON_ALIAS) VALUES(30,'SHELL');