/*TABLA ENTRENAMIENTO*/

CREATE TABLE ENTRENAMIENTO
(
	ENTRENAMIENTO_ID serial PRIMARY KEY,
	ENTRENAMIENTO_F_INICIO date,
	ENTRENAMIENTO_F_TERMINO date,
	BATALLON_ID BIGINT UNSIGNED NOT NULL,
	CALIFICACION_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT ENTRENAMIENTO_BATALLON_FK FOREIGN KEY (BATALLON_ID) REFERENCES BATALLON (BATALLON_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ENTRENAMIENTO_CALIFICACION_FK FOREIGN KEY (CALIFICACION_ID) REFERENCES CALIFICACION (CALIFICACION_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE
);

/*INGRESAR VALORES EN ENTRENAMIENTO*/

INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2020-2-5','2020-2-10',1,2);
INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2020-3-7','2020-3-15',1,1);
INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2020-3-20','2020-3-25',1,2);
INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2020-4-10','2020-4-20',1,3);

INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2018-1-10','2018-1-20',2,3);
INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2018-6-7','2018-6-23',2,3);
INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2019-12-1','2019-12-20',2,3);
INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2020-4-10','2020-4-22',2,3);

INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2017-3-9','2017-3-15',3,1);
INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2017-8-7','2017-8-30',3,1);
INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2019-12-31','2020-1-15',3,2);
INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2020-3-7','2020-3-26',3,2);

INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2015-2-15','2015-3-1',4,2);
INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2016-5-10','2016-6-2',4,1);
INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2016-7-3','2016-7-20',4,2);
INSERT INTO ENTRENAMIENTO (ENTRENAMIENTO_F_INICIO,ENTRENAMIENTO_F_TERMINO,BATALLON_ID,CALIFICACION_ID)
VALUES ('2018-1-7','2018-1-30',4,3);