/*TABLA PETICION ASCENSO*/

CREATE TABLE PETICION_ASCENSO
(
	PETICION_ASCENSO_ID serial PRIMARY KEY,
	ASPIRANTE_ID BIGINT UNSIGNED NOT NULL,
	PETICION_ASCENSO_FECHA date,
	PETICION_ASCENSO_N_T_ENCONTRADOS smallint,
	RANGO_ACTUAL_ID BIGINT UNSIGNED NOT NULL,
	RANGO_ASCENDER_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT ASCENSO_RANGO_ACTUAL_FK FOREIGN KEY (RANGO_ACTUAL_ID) REFERENCES RANGO (RANGO_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ASCENSO_RANGO_ASCENDER_FK FOREIGN KEY (RANGO_ASCENDER_ID) REFERENCES RANGO (RANGO_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ASCENSO_SOLDADO_FK FOREIGN KEY (ASPIRANTE_ID) REFERENCES SOLDADO (SOLDADO_ID) 
	ON DELETE CASCADE ON UPDATE CASCADE
);

/*INGRESAR VALORES PETICION DE ASCENSO*/

INSERT INTO PETICION_ASCENSO (ASPIRANTE_ID,PETICION_ASCENSO_FECHA,PETICION_ASCENSO_N_T_ENCONTRADOS,RANGO_ACTUAL_ID,RANGO_ASCENDER_ID)
VALUES (1,'2015-07-08',0,5,6);

INSERT INTO PETICION_ASCENSO (ASPIRANTE_ID,PETICION_ASCENSO_FECHA,PETICION_ASCENSO_N_T_ENCONTRADOS,RANGO_ACTUAL_ID,RANGO_ASCENDER_ID)
VALUES (10,'2004-07-08',0,1,2);

INSERT INTO PETICION_ASCENSO (ASPIRANTE_ID,PETICION_ASCENSO_FECHA,PETICION_ASCENSO_N_T_ENCONTRADOS,RANGO_ACTUAL_ID,RANGO_ASCENDER_ID)
VALUES (14,'2006-12-01',0,1,2);

INSERT INTO PETICION_ASCENSO (ASPIRANTE_ID,PETICION_ASCENSO_FECHA,PETICION_ASCENSO_N_T_ENCONTRADOS,RANGO_ACTUAL_ID,RANGO_ASCENDER_ID)
VALUES (17,'2009-03-08',4,1,2);

INSERT INTO PETICION_ASCENSO (ASPIRANTE_ID,PETICION_ASCENSO_FECHA,PETICION_ASCENSO_N_T_ENCONTRADOS,RANGO_ACTUAL_ID,RANGO_ASCENDER_ID)
VALUES (21,'1991-01-01',0,1,2);

INSERT INTO PETICION_ASCENSO (ASPIRANTE_ID,PETICION_ASCENSO_FECHA,PETICION_ASCENSO_N_T_ENCONTRADOS,RANGO_ACTUAL_ID,RANGO_ASCENDER_ID)
VALUES (9,'2007-01-01',3,1,2);

INSERT INTO PETICION_ASCENSO (ASPIRANTE_ID,PETICION_ASCENSO_FECHA,PETICION_ASCENSO_N_T_ENCONTRADOS,RANGO_ACTUAL_ID,RANGO_ASCENDER_ID)
VALUES (9,'2008-01-01',0,1,2);

INSERT INTO PETICION_ASCENSO (ASPIRANTE_ID,PETICION_ASCENSO_FECHA,PETICION_ASCENSO_N_T_ENCONTRADOS,RANGO_ACTUAL_ID,RANGO_ASCENDER_ID)
VALUES (23,'2012-01-01',1,1,2);

INSERT INTO PETICION_ASCENSO (ASPIRANTE_ID,PETICION_ASCENSO_FECHA,PETICION_ASCENSO_N_T_ENCONTRADOS,RANGO_ACTUAL_ID,RANGO_ASCENDER_ID)
VALUES (16,'1999-07-23',7,1,2);