/*TRIGGER PARA GUARDAR EL HISTORIAL DE TATUAJES QUE HA TENIDO UN SOLDADO Y QUE UN SOLDADO NO PUEDA TENER MENOS DE 0 TATUAJES*/

DELIMITER $$

    CREATE TRIGGER SOLDADO_TATUAJE_BU BEFORE UPDATE ON SOLDADO 
    FOR EACH ROW
    BEGIN 
        IF ( NEW.SOLDADO_N_TATUAJE < 0) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO PUEDE INGRESAR VALORES MENORES A 0';
        END IF;
        IF (NEW.SOLDADO_N_TATUAJE != OLD.SOLDADO_N_TATUAJE) THEN
            INSERT INTO historial_tatuaje(S_ID,S_N_ANTERIOR_TATUAJES,S_N_NUEVO_TATUAJES,HT_FECHA)
            VALUES (OLD.SOLDADO_ID,OLD.SOLDADO_N_TATUAJE,NEW.SOLDADO_N_TATUAJE, NOW());
        END IF;
    END$$

DELIMITER ;